added check if geninfocontrib_h.sh is iso-8859-1
git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@38722 379a1393-f5fb-40a0-bcee-ef074d9b53f7

diff --git a/vice/src/Makefile.am b/vice/src/Makefile.am
--- a/vice/src/Makefile.am
+++ b/vice/src/Makefile.am
@@ -595,8 +595,12 @@ svnversion.h.indirect:
 
 svnversion.h: svnversion.h.indirect
 
-infocontrib.h:	$(top_srcdir)/doc/vice.texi $(srcdir)/buildtools/infocontrib.sed
+infocontrib.h:	$(srcdir)/buildtools/geninfocontrib_h.sh $(top_srcdir)/doc/vice.texi $(srcdir)/buildtools/infocontrib.sed
 	@echo "generating infocontrib.h..."
+	if [ "`file --mime-encoding $(srcdir)/buildtools/geninfocontrib_h.sh`" != "$(srcdir)/buildtools/geninfocontrib_h.sh: iso-8859-1" ]; then \
+		echo "ERROR: geninfocontrib_h.sh contains content that is not valid iso-8859-1" >&2; \
+		false; \
+	fi
 	$(SHELL) $(srcdir)/buildtools/geninfocontrib_h.sh infocontrib.h <$(top_srcdir)/doc/vice.texi | $(srcdir)/sedinfocontrib_h.sh $(srcdir)/buildtools/infocontrib.sed >infocontrib.h
 	$(SHELL) $(srcdir)/buildtools/geninfocontrib_h.sh AUTHORS | $(srcdir)/sedinfocontrib_h.sh $(srcdir)/buildtools/infocontrib.sed >../AUTHORS
 	sed -e 's/\\/@/g' -e 's/ /%/g' <$(top_srcdir)/README >./README.tmp
