This commit was generated by cvs2svn to compensate for changes in r2305, which included commits to RCS files with non-trunk default branches.
git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@2306 379a1393-f5fb-40a0-bcee-ef074d9b53f7

diff --git a/vice/configure.in b/vice/configure.in
--- a/vice/configure.in
+++ b/vice/configure.in
@@ -6,7 +6,7 @@ dnl Process this file with GNU autoconf to produce a configure script.
 dnl
 
 AC_INIT(src/maincpu.c)
-AM_INIT_AUTOMAKE(vice, 0.14.2.42)
+AM_INIT_AUTOMAKE(vice, 0.14.2.43)
 AM_CONFIG_HEADER(src/config.h)
 
 dnl Try to find out which system we are on...
@@ -21,6 +21,7 @@ AC_ARG_ENABLE(24bpp,[  --enable-24bpp          enable 24-bit only display depth 
 AC_ARG_ENABLE(textfield,[  --disable-textfield     disable enhanced text field widget])
 AC_ARG_WITH(xaw3d, [  --with-xaw3d            use Xaw3d library instead of plain Xaw])
 AC_ARG_WITH(readline, [  --without-readline      do not try to use the system's readline library])
+AC_ARG_WITH(resid, [  --with-resid=PATH       link with the reSID engine located at PATH])
 
 if test x"$enable_autobpp" = "xyes"; then
   AC_DEFINE(X_DISPLAY_DEPTH, 0)
@@ -112,7 +113,33 @@ else
 
   dnl This is only possible on Unix (for now).
   AC_DEFINE(HAVE_RS232)
+  AC_DEFINE(HAVE_PRINTER)
 fi
+
+dnl Setup reSID compilation.  We need a C++ compiler for this.
+
+if test x"$with_resid" != "xno" -a x"$with_resid" != "x"; then
+   echo "Attempting to configure reSID support at \`$with_resid'"
+   if test ! -f "$with_resid/resid.h"; then
+     echo "Cannot find \`$with_resid/resid.h', giving up."
+     exit 1
+   fi
+   if test ! -f "$with_resid/libmos6581.h"; then
+     echo "Cannot find \`$with_resid/libmos6581.h', giving up."
+     exit 1
+   fi
+   AC_PROG_CXX
+   AC_DEFINE(HAVE_RESID)
+   RESID_LIBS="$with_resid/libmos6581.a"
+   RESID_INCLUDES="-I$with_resid"
+   AM_CONDITIONAL(HAVE_RESID, true)
+else
+   RESID_LIBS=""
+   RESID_INCLUDES=""
+   AM_CONDITIONAL(HAVE_RESID, false)
+fi
+AC_SUBST(RESID_LIBS)
+AC_SUBST(RESID_INCLUDES)
 
 dnl Check for needed external programs.
 
@@ -334,7 +361,7 @@ if [[ x"$is_dos" != "xyes" ]]; then
   AC_DEFINE(HAVE_READLINE)
 else
   ARCH_INCLUDES="-I\$(top_srcdir)/src/arch/msdos/"
-  ARCH_LIBS="\$(top_builddir)/src/arch/msdos/libarch.a $(ARCH_LIBS)"
+  ARCH_LIBS="\$(top_builddir)/src/arch/msdos/libarch.a \$(ARCH_LIBS)"
   AM_CONDITIONAL(MSDOS_COMPILE, true)
 fi
 
