This commit was generated by cvs2svn to compensate for changes in r15459, which included commits to RCS files with non-trunk default branches.
git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@15460 379a1393-f5fb-40a0-bcee-ef074d9b53f7

diff --git a/vice/configure b/vice/configure
--- a/vice/configure
+++ b/vice/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all src/resid"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE build build_cpu build_vendor build_os host host_cpu host_vendor host_os GNOMEUI_TRUE GNOMEUI_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE HAVE_RS232_TRUE HAVE_RS232_FALSE HAVE_RAWDRIVE_TRUE HAVE_RAWDRIVE_FALSE USE_MIDAS_SOUND_TRUE USE_MIDAS_SOUND_FALSE DOS_OR_WIN_TRUE DOS_OR_WIN_FALSE CPP AR RANLIB ac_ct_RANLIB LN_S YACC LEX LEXLIB LEX_OUTPUT_ROOT GMOFILES POFILES EGREP MSGFMT GMSGFMT XGETTEXT USE_INCLUDED_LIBINTL CATALOGS DATADIRNAME INSTOBJEXT INTLDEPS INTLLIBS INTLOBJS POSUB GENCAT MKINSTALLDIRS CATOBJEXT USE_NLS NLS_LOCALEDIR PERL artsc_config sdl_config cxx CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP subdirs LINKCC HAVE_RESID_TRUE HAVE_RESID_FALSE RESID_DIR RESID_LIBS RESID_INCLUDES RESID_DEP JOY_OBJS SOUND_DRIVERS SOUND_LIBS LIBOBJS NEED_READLINE_TRUE NEED_READLINE_FALSE READLINE GFXOUTPUT_DRIVERS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS FULLSCREEN_DRIVERS WINDRES HAVE_REALDEVICE_TRUE HAVE_REALDEVICE_FALSE x64_LDFLAGS x128_LDFLAGS xvic_LDFLAGS xpet_LDFLAGS xplus4_LDFLAGS xcbm2_LDFLAGS X64_WINRES X128_WINRES XVIC_WINRES XPET_WINRES XPLUS4_WINRES XCBM2_WINRES UNIX_COMPILE_TRUE UNIX_COMPILE_FALSE WIN32_COMPILE_TRUE WIN32_COMPILE_FALSE MSDOS_COMPILE_TRUE MSDOS_COMPILE_FALSE RISCOS_COMPILE_TRUE RISCOS_COMPILE_FALSE OS2_COMPILE_TRUE OS2_COMPILE_FALSE BEOS_COMPILE_TRUE BEOS_COMPILE_FALSE HAVE_READLINE ARCH_INCLUDES ARCH_LIBS ARCH_DIR SOUND_USS_OBJ SOUND_SGI_OBJ SOUND_HPUX_OBJ SOUND_AIX_OBJ SOUND_MIDAS_OBJ SOUND_SDL_OBJ BINDIR LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE build build_cpu build_vendor build_os host host_cpu host_vendor host_os GNOMEUI_TRUE GNOMEUI_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE HAVE_RS232_TRUE HAVE_RS232_FALSE HAVE_RAWDRIVE_TRUE HAVE_RAWDRIVE_FALSE HAVE_REALDEVICE_TRUE HAVE_REALDEVICE_FALSE USE_MIDAS_SOUND_TRUE USE_MIDAS_SOUND_FALSE DOS_OR_WIN_TRUE DOS_OR_WIN_FALSE CPP AR RANLIB ac_ct_RANLIB LN_S YACC LEX LEXLIB LEX_OUTPUT_ROOT GMOFILES POFILES EGREP MSGFMT GMSGFMT XGETTEXT USE_INCLUDED_LIBINTL CATALOGS DATADIRNAME INSTOBJEXT INTLDEPS INTLLIBS INTLOBJS POSUB GENCAT MKINSTALLDIRS CATOBJEXT USE_NLS NLS_LOCALEDIR PERL artsc_config sdl_config cxx CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP subdirs LINKCC HAVE_RESID_TRUE HAVE_RESID_FALSE RESID_DIR RESID_LIBS RESID_INCLUDES RESID_DEP JOY_OBJS SOUND_DRIVERS SOUND_LIBS LIBOBJS NEED_READLINE_TRUE NEED_READLINE_FALSE READLINE GFXOUTPUT_DRIVERS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS FULLSCREEN_DRIVERS WINDRES x64_LDFLAGS x128_LDFLAGS xvic_LDFLAGS xpet_LDFLAGS xplus4_LDFLAGS xcbm2_LDFLAGS X64_WINRES X128_WINRES XVIC_WINRES XPET_WINRES XPLUS4_WINRES XCBM2_WINRES UNIX_COMPILE_TRUE UNIX_COMPILE_FALSE WIN32_COMPILE_TRUE WIN32_COMPILE_FALSE MSDOS_COMPILE_TRUE MSDOS_COMPILE_FALSE RISCOS_COMPILE_TRUE RISCOS_COMPILE_FALSE OS2_COMPILE_TRUE OS2_COMPILE_FALSE BEOS_COMPILE_TRUE BEOS_COMPILE_FALSE HAVE_READLINE ARCH_INCLUDES ARCH_LIBS ARCH_DIR SOUND_USS_OBJ SOUND_SGI_OBJ SOUND_HPUX_OBJ SOUND_AIX_OBJ SOUND_MIDAS_OBJ SOUND_SDL_OBJ BINDIR LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1568,7 +1568,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=vice
- VERSION=1.14.36
+ VERSION=1.14.37
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3013,6 +3013,21 @@ _ACEOF
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_TFE
 _ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENCBM
+_ACEOF
+
+
+
+if true; then
+  HAVE_REALDEVICE_TRUE=
+  HAVE_REALDEVICE_FALSE='#'
+else
+  HAVE_REALDEVICE_TRUE='#'
+  HAVE_REALDEVICE_FALSE=
+fi
 
 
 
@@ -16204,6 +16219,11 @@ fi
 
 
   if test x"$ac_cv_header_opencbm_h" = "xyes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENCBM_H
+_ACEOF
+
     echo "$as_me:$LINENO: checking for cbm_get_eoi in -lopencbm" >&5
 echo $ECHO_N "checking for cbm_get_eoi in -lopencbm... $ECHO_C" >&6
 if test "${ac_cv_lib_opencbm_cbm_get_eoi+set}" = set; then
@@ -16267,9 +16287,6 @@ _ACEOF
 
 fi
 
-  fi
-fi
-
 
 
 if test x"$ac_cv_lib_opencbm_cbm_get_eoi" = "xyes"; then
@@ -16280,6 +16297,8 @@ else
   HAVE_REALDEVICE_FALSE=
 fi
 
+  fi
+fi
 
 
 
@@ -16942,6 +16961,13 @@ if test -z "${HAVE_RAWDRIVE_TRUE}" && test -z "${HAVE_RAWDRIVE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_RAWDRIVE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_RAWDRIVE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_REALDEVICE_TRUE}" && test -z "${HAVE_REALDEVICE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_REALDEVICE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_REALDEVICE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -17935,6 +17961,8 @@ s,@HAVE_RS232_TRUE@,$HAVE_RS232_TRUE,;t t
 s,@HAVE_RS232_FALSE@,$HAVE_RS232_FALSE,;t t
 s,@HAVE_RAWDRIVE_TRUE@,$HAVE_RAWDRIVE_TRUE,;t t
 s,@HAVE_RAWDRIVE_FALSE@,$HAVE_RAWDRIVE_FALSE,;t t
+s,@HAVE_REALDEVICE_TRUE@,$HAVE_REALDEVICE_TRUE,;t t
+s,@HAVE_REALDEVICE_FALSE@,$HAVE_REALDEVICE_FALSE,;t t
 s,@USE_MIDAS_SOUND_TRUE@,$USE_MIDAS_SOUND_TRUE,;t t
 s,@USE_MIDAS_SOUND_FALSE@,$USE_MIDAS_SOUND_FALSE,;t t
 s,@DOS_OR_WIN_TRUE@,$DOS_OR_WIN_TRUE,;t t
@@ -18000,8 +18028,6 @@ s,@X_LIBS@,$X_LIBS,;t t
 s,@X_EXTRA_LIBS@,$X_EXTRA_LIBS,;t t
 s,@FULLSCREEN_DRIVERS@,$FULLSCREEN_DRIVERS,;t t
 s,@WINDRES@,$WINDRES,;t t
-s,@HAVE_REALDEVICE_TRUE@,$HAVE_REALDEVICE_TRUE,;t t
-s,@HAVE_REALDEVICE_FALSE@,$HAVE_REALDEVICE_FALSE,;t t
 s,@x64_LDFLAGS@,$x64_LDFLAGS,;t t
 s,@x128_LDFLAGS@,$x128_LDFLAGS,;t t
 s,@xvic_LDFLAGS@,$xvic_LDFLAGS,;t t
