2008-05-07  Spiro Trikaliotis  <spiro.trikaliotis@gmx.de>
	* Version 1.22.14.



git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@18770 379a1393-f5fb-40a0-bcee-ef074d9b53f7

diff --git a/vice/configure b/vice/configure
--- a/vice/configure
+++ b/vice/configure
@@ -777,6 +777,9 @@ FFMPEG_INCLUDES
 FFMPEG_LIBS
 DOS_TFE_PCAP_LIB
 TFE_LIBS
+FCCACHE
+HAVE_FC_CACHE_TRUE
+HAVE_FC_CACHE_FALSE
 WINDRES
 WRC
 SOUND_DRIVERS
@@ -1960,7 +1963,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 VICE_VERSION_MAJOR=1
 VICE_VERSION_MINOR=22
-VICE_VERSION_BUILD=13
+VICE_VERSION_BUILD=14
 
 
 
@@ -18204,6 +18207,76 @@ fi
 
 fi
 
+for ac_prog in fc-cache
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_FCCACHE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $FCCACHE in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_FCCACHE="$FCCACHE" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_FCCACHE="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+FCCACHE=$ac_cv_path_FCCACHE
+if test -n "$FCCACHE"; then
+  { echo "$as_me:$LINENO: result: $FCCACHE" >&5
+echo "${ECHO_T}$FCCACHE" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$FCCACHE" && break
+done
+test -n "$FCCACHE" || FCCACHE="false"
+
+if test x"$FCCACHE" = "xfalse"; then
+
+
+if false; then
+  HAVE_FC_CACHE_TRUE=
+  HAVE_FC_CACHE_FALSE='#'
+else
+  HAVE_FC_CACHE_TRUE='#'
+  HAVE_FC_CACHE_FALSE=
+fi
+
+else
+
+
+if true; then
+  HAVE_FC_CACHE_TRUE=
+  HAVE_FC_CACHE_FALSE='#'
+else
+  HAVE_FC_CACHE_TRUE='#'
+  HAVE_FC_CACHE_FALSE=
+fi
+
+fi
+
 if test x"$is_amigaos4" = "xyes"; then
   { echo "$as_me:$LINENO: checking whether devices/timer.h defines TimeVal" >&5
 echo $ECHO_N "checking whether devices/timer.h defines TimeVal... $ECHO_C" >&6; }
@@ -28496,6 +28569,20 @@ echo "$as_me: error: conditional \"CROSS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_FC_CACHE_TRUE}" && test -z "${HAVE_FC_CACHE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_FC_CACHE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_FC_CACHE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_FC_CACHE_TRUE}" && test -z "${HAVE_FC_CACHE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_FC_CACHE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_FC_CACHE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${NEED_READLINE_TRUE}" && test -z "${NEED_READLINE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"NEED_READLINE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -30395,6 +30482,9 @@ FFMPEG_INCLUDES!$FFMPEG_INCLUDES$ac_delim
 FFMPEG_LIBS!$FFMPEG_LIBS$ac_delim
 DOS_TFE_PCAP_LIB!$DOS_TFE_PCAP_LIB$ac_delim
 TFE_LIBS!$TFE_LIBS$ac_delim
+FCCACHE!$FCCACHE$ac_delim
+HAVE_FC_CACHE_TRUE!$HAVE_FC_CACHE_TRUE$ac_delim
+HAVE_FC_CACHE_FALSE!$HAVE_FC_CACHE_FALSE$ac_delim
 WINDRES!$WINDRES$ac_delim
 WRC!$WRC$ac_delim
 SOUND_DRIVERS!$SOUND_DRIVERS$ac_delim
@@ -30422,9 +30512,6 @@ GTKGL_CFLAGS!$GTKGL_CFLAGS$ac_delim
 GTKGL_LIBS!$GTKGL_LIBS$ac_delim
 VICE_SYNC!$VICE_SYNC$ac_delim
 FULLSCREEN_DRIVERS!$FULLSCREEN_DRIVERS$ac_delim
-HAVE_REALDEVICE_TRUE!$HAVE_REALDEVICE_TRUE$ac_delim
-HAVE_REALDEVICE_FALSE!$HAVE_REALDEVICE_FALSE$ac_delim
-x64_LDFLAGS!$x64_LDFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -30466,6 +30553,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+HAVE_REALDEVICE_TRUE!$HAVE_REALDEVICE_TRUE$ac_delim
+HAVE_REALDEVICE_FALSE!$HAVE_REALDEVICE_FALSE$ac_delim
+x64_LDFLAGS!$x64_LDFLAGS$ac_delim
 x128_LDFLAGS!$x128_LDFLAGS$ac_delim
 xvic_LDFLAGS!$xvic_LDFLAGS$ac_delim
 xpet_LDFLAGS!$xpet_LDFLAGS$ac_delim
@@ -30536,7 +30626,7 @@ BINDIR!$BINDIR$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 68; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 71; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
