check should also pass when the file is plain ascii
git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@42828 379a1393-f5fb-40a0-bcee-ef074d9b53f7

diff --git a/vice/doc/Makefile.am b/vice/doc/Makefile.am
--- a/vice/doc/Makefile.am
+++ b/vice/doc/Makefile.am
@@ -44,8 +44,10 @@ endif
 
 .vice-texi-charset-ok:	$(srcdir)/vice.texi
 	@if [ "`file --mime-encoding $<`" != "$<: iso-8859-1" ]; then \
-		echo "ERROR: vice.texi contains content that is not valid iso-8859-x" >&2; \
-		false; \
+		if [ "`file --mime-encoding $<`" != "$<: us-ascii" ]; then \
+			echo "ERROR: vice.texi contains content that is not valid iso-8859-x" >&2; \
+			false; \
+		fi; \
 	fi
 	@touch .vice-texi-charset-ok
 
