Added simple check that vice.texi is valid ISO-8859-1 during PDF generation. Should probably be moved somewhere where it can run for all cases.
git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@36588 379a1393-f5fb-40a0-bcee-ef074d9b53f7

diff --git a/vice/doc/Makefile.am b/vice/doc/Makefile.am
--- a/vice/doc/Makefile.am
+++ b/vice/doc/Makefile.am
@@ -67,6 +67,10 @@ $(builddir)/vice.txt:		$(srcdir)/vice.texi
 
 $(builddir)/vice.pdf:	$(srcdir)/vice.texi
 if BUILD_PDF
+	if [ "`file --mime-encoding vice.texi`" != "vice.texi: iso-8859-1" ]; then \
+		echo "ERROR: vice.texi content not ios-8859-1" >&2; \
+		false; \
+	fi
 	LANG=C sed 's/@heading NO WARRANTY/@center NO WARRANTY/g' <$(srcdir)/vice.texi >vicepdf.texi
 	LANG=C $(TEXI2DVI) -q --clean --pdf "--texinfo=@set $(PLATFORM_DOX_FLAGS) " -o $(builddir)/vice.pdf vicepdf.texi
 		rm -f vicepdf.texi
